/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blue_white_wavy_mechanical_keyboard.glb 
Author: Rendy K (https://sketchfab.com/RendyK)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-white-wavy-mechanical-keyboard-669b2d047b444fdf949d146a6b083522
Title: Blue White Wavy Mechanical Keyboard
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function KeyboardModel(props) {
  const { nodes, materials } = useGLTF('/models/blue_white_wavy_mechanical_keyboard.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.327, 0.074, 0.066]} rotation={[0.024, 0, 0]} scale={[0.278, 0.075, 0.106]}>
        <group position={[-0.002, -0.806, -0.141]} rotation={[0.004, 0, 0]} scale={[3.601, 13.356, 9.431]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials.Alumunium_Blue_Sky_Case} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Sticker.001']} />
        </group>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Wavy_Keycaps} position={[-0.004, -0.564, -0.079]} scale={[0.119, 0.44, 0.31]} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Rubber_Feet} position={[0, -0.972, 0.734]} rotation={[-0.026, 0, 0]} scale={[0.027, 0.051, 0.051]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Blue_RGB} position={[0.007, -0.713, 0.008]} rotation={[-0.006, 0, 0]} scale={[0.3, 1.117, 0.809]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/blue_white_wavy_mechanical_keyboard.glb')
