/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 caffe_bernini.glb 
Author: Jellepostma (https://sketchfab.com/Jellepostma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/caffe-bernini-30aec62d7c7f4c58acac204d2eeb49bd
Title: Caffè Bernini
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CaffeBerniniModel(props) {
  const { nodes, materials } = useGLTF('/models/caffe_bernini.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Outside_Outside_0.geometry} material={materials.Outside} />
        <mesh geometry={nodes.Outside_Outside_0_1.geometry} material={materials.Outside} />
        <mesh geometry={nodes.Outside_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Outside_Outside_E_0.geometry} material={materials.Outside_E} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Inside_Inside_0.geometry} material={materials.Inside} />
        <mesh geometry={nodes.Inside_Inside_0_1.geometry} material={materials.Inside} />
        <mesh geometry={nodes.Inside_Inside_0_2.geometry} material={materials.Inside} />
        <mesh geometry={nodes.Inside_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Inside_Inside_E_0.geometry} material={materials.Inside_E} />
        <mesh geometry={nodes.Inside_Aeropress_0.geometry} material={materials.Aeropress} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Stuff_Stuff_0.geometry} material={materials.Stuff} />
        <mesh geometry={nodes.Stuff_Stuff_0_1.geometry} material={materials.Stuff} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/caffe_bernini.glb')
