/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coffee_bean.glb 
Author: Azamuki (https://sketchfab.com/Azamuki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-bean-a7e9fc310f9b4fd3aac55f31bf9d6126
Title: Coffee Bean
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CoffeeBeanModel(props) {
  const { nodes, materials } = useGLTF('/models/coffee_bean.glb')
  return (
    <group {...props} scale={1} position={[0, 0, 0]}>
      <mesh
        geometry={nodes.Coffebean_Coffebean_0.geometry}
        material={materials.Coffebean}
      />
      <mesh
        geometry={nodes.Drop_Drop_0.geometry}
        material={materials.Drop}
      >
        <meshStandardMaterial {...materials.Drop} side={2} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/coffee_bean.glb')
