/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coffee_cup.glb -T 
Files: coffee_cup.glb [16.16MB] > F:\Devs\3D_portfolio\public\models\coffee_cup-transformed.glb [1.79MB] (89%)
Author: nyx-abu (https://sketchfab.com/soundaryaraja48)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-e6de295181494fb0a89a34138737599b
Title: Coffee cup
*/

import React, {useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function CoffeeCupModel(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/coffee_cup.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // This finds the first animation clip in your GLB
    const action = Object.values(actions)[0]
    
    if (action) {
      action.reset().play()
    }

    // Cleanup: stops the animation if the component unmounts
    return () => action?.fadeOut(0.5)
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null} frustumCulled={false}>
      <group name="Sketchfab_Scene">
        <group name="Object_3" scale={0.002}>
          <group name="Object_4" position={[1.031, 704.397, -30.282]} rotation={[0.268, -0.06, -0.068]} scale={100}>
            <group name="TimeframeMainGroup_1">
              <group name="Object_6">
                <mesh name="Cube_001_2_0" geometry={nodes.Cube_001_2_0.geometry} material={materials.Cube_001} />
              </group>
            </group>
          </group>
          <group name="Object_108" position={[34.006, 482.328, -27.318]} rotation={[0.834, 0.063, 2.861]} scale={100}>
            <group name="TimeframeMainGroup_2">
              <group name="Object_110">
                <mesh name="Cube_008_7_0" geometry={nodes.Cube_008_7_0.geometry} material={materials.Cube_008} />
              </group>
            </group>
          </group>
          <group name="Object_112" position={[-19.094, 850.85, 41.099]} rotation={[0.954, -0.215, -1.166]} scale={100}>
            <group name="TimeframeMainGroup_3">
              <group name="Object_114">
                <mesh name="Cube_007_9_0" geometry={nodes.Cube_007_9_0.geometry} material={materials.Cube_008} />
              </group>
            </group>
          </group>
        </group>
        <group name="TimeframeMainGroup" position={[0, 0.652, 0]} scale={[0.381, 0.65, 0.381]}>
          <group name="Object_10">
            <mesh name="Cube_5_0" scale={0.99} geometry={nodes.Cube_5_0.geometry} material={materials.Cube} material-transparent={false} material-depthWrite={true}>
              <meshStandardMaterial 
                {...materials.Cube} 
                polygonOffset 
                polygonOffsetFactor={-1} // Pushes this mesh slightly "forward" in the calculation
              />
            </mesh> 
          </group>
          <group name="Object_12" scale={0}>
            <mesh name="Cube_5_1" geometry={nodes.Cube_5_1.geometry} material={materials.Cube} visible={false}/>
          </group>
          <group name="Object_14" scale={0}>
            <mesh name="Cube_5_2" geometry={nodes.Cube_5_2.geometry} material={materials.Cube} />
          </group>
          <group name="Object_16" scale={0}>
            <mesh name="Cube_5_3" geometry={nodes.Cube_5_3.geometry} material={materials.Cube} />
          </group>
          <group name="Object_18" scale={0}>
            <mesh name="Cube_5_4" geometry={nodes.Cube_5_4.geometry} material={materials.Cube} />
          </group>
          <group name="Object_20" scale={0}>
            <mesh name="Cube_5_5" geometry={nodes.Cube_5_5.geometry} material={materials.Cube} />
          </group>
          <group name="Object_22" scale={0}>
            <mesh name="Cube_5_6" geometry={nodes.Cube_5_6.geometry} material={materials.Cube} />
          </group>
          <group name="Object_24" scale={0}>
            <mesh name="Cube_5_7" geometry={nodes.Cube_5_7.geometry} material={materials.Cube} />
          </group>
          <group name="Object_26" scale={0}>
            <mesh name="Cube_5_8" geometry={nodes.Cube_5_8.geometry} material={materials.Cube} />
          </group>
          <group name="Object_28" scale={0}>
            <mesh name="Cube_5_9" geometry={nodes.Cube_5_9.geometry} material={materials.Cube} />
          </group>
          <group name="Object_30" scale={0}>
            <mesh name="Cube_5_10" geometry={nodes.Cube_5_10.geometry} material={materials.Cube} />
          </group>
          <group name="Object_32" scale={0}>
            <mesh name="Cube_5_11" geometry={nodes.Cube_5_11.geometry} material={materials.Cube} />
          </group>
          <group name="Object_34" scale={0}>
            <mesh name="Cube_5_12" geometry={nodes.Cube_5_12.geometry} material={materials.Cube} />
          </group>
          <group name="Object_36" scale={0}>
            <mesh name="Cube_5_13" geometry={nodes.Cube_5_13.geometry} material={materials.Cube} />
          </group>
          <group name="Object_38" scale={0}>
            <mesh name="Cube_5_14" geometry={nodes.Cube_5_14.geometry} material={materials.Cube} />
          </group>
          <group name="Object_40" scale={0}>
            <mesh name="Cube_5_15" geometry={nodes.Cube_5_15.geometry} material={materials.Cube} />
          </group>
          <group name="Object_42" scale={0}>
            <mesh name="Cube_5_16" geometry={nodes.Cube_5_16.geometry} material={materials.Cube} />
          </group>
          <group name="Object_44" scale={0}>
            <mesh name="Cube_5_17" geometry={nodes.Cube_5_17.geometry} material={materials.Cube} />
          </group>
          <group name="Object_46" scale={0}>
            <mesh name="Cube_5_18" geometry={nodes.Cube_5_18.geometry} material={materials.Cube} />
          </group>
          <group name="Object_48" scale={0}>
            <mesh name="Cube_5_19" geometry={nodes.Cube_5_19.geometry} material={materials.Cube} />
          </group>
          <group name="Object_50" scale={0}>
            <mesh name="Cube_5_20" geometry={nodes.Cube_5_20.geometry} material={materials.Cube} />
          </group>
          <group name="Object_52" scale={0}>
            <mesh name="Cube_5_21" geometry={nodes.Cube_5_21.geometry} material={materials.Cube} />
          </group>
          <group name="Object_54" scale={0}>
            <mesh name="Cube_5_22" geometry={nodes.Cube_5_22.geometry} material={materials.Cube} />
          </group>
          <group name="Object_56" scale={0}>
            <mesh name="Cube_5_23" geometry={nodes.Cube_5_23.geometry} material={materials.Cube} />
          </group>
          <group name="Object_58" scale={0}>
            <mesh name="Cube_5_24" geometry={nodes.Cube_5_24.geometry} material={materials.Cube} />
          </group>
          <group name="Object_60" scale={0}>
            <mesh name="Cube_5_25" geometry={nodes.Cube_5_25.geometry} material={materials.Cube} />
          </group>
          <group name="Object_62" scale={0}>
            <mesh name="Cube_5_26" geometry={nodes.Cube_5_26.geometry} material={materials.Cube} />
          </group>
          <group name="Object_64" scale={0}>
            <mesh name="Cube_5_27" geometry={nodes.Cube_5_27.geometry} material={materials.Cube} />
          </group>
          <group name="Object_66" scale={0}>
            <mesh name="Cube_5_28" geometry={nodes.Cube_5_28.geometry} material={materials.Cube} />
          </group>
          <group name="Object_68" scale={0}>
            <mesh name="Cube_5_29" geometry={nodes.Cube_5_29.geometry} material={materials.Cube} />
          </group>
          <group name="Object_70" scale={0}>
            <mesh name="Cube_5_30" geometry={nodes.Cube_5_30.geometry} material={materials.Cube} />
          </group>
          <group name="Object_72" scale={0}>
            <mesh name="Cube_5_31" geometry={nodes.Cube_5_31.geometry} material={materials.Cube} />
          </group>
          <group name="Object_74" scale={0}>
            <mesh name="Cube_5_32" geometry={nodes.Cube_5_32.geometry} material={materials.Cube} />
          </group>
          <group name="Object_76" scale={0}>
            <mesh name="Cube_5_33" geometry={nodes.Cube_5_33.geometry} material={materials.Cube} />
          </group>
          <group name="Object_78" scale={0}>
            <mesh name="Cube_5_34" geometry={nodes.Cube_5_34.geometry} material={materials.Cube} />
          </group>
          <group name="Object_80" scale={0}>
            <mesh name="Cube_5_35" geometry={nodes.Cube_5_35.geometry} material={materials.Cube} />
          </group>
          <group name="Object_82" scale={0}>
            <mesh name="Cube_5_36" geometry={nodes.Cube_5_36.geometry} material={materials.Cube} />
          </group>
          <group name="Object_84" scale={0}>
            <mesh name="Cube_5_37" geometry={nodes.Cube_5_37.geometry} material={materials.Cube} />
          </group>
          <group name="Object_86" scale={0}>
            <mesh name="Cube_5_38" geometry={nodes.Cube_5_38.geometry} material={materials.Cube} />
          </group>
          <group name="Object_88" scale={0}>
            <mesh name="Cube_5_39" geometry={nodes.Cube_5_39.geometry} material={materials.Cube} />
          </group>
          <group name="Object_90" scale={0}>
            <mesh name="Cube_5_40" geometry={nodes.Cube_5_40.geometry} material={materials.Cube} />
          </group>
          <group name="Object_92" scale={0}>
            <mesh name="Cube_5_41" geometry={nodes.Cube_5_41.geometry} material={materials.Cube} />
          </group>
          <group name="Object_94" scale={0}>
            <mesh name="Cube_5_42" geometry={nodes.Cube_5_42.geometry} material={materials.Cube} />
          </group>
          <group name="Object_96" scale={0}>
            <mesh name="Cube_5_43" geometry={nodes.Cube_5_43.geometry} material={materials.Cube} />
          </group>
          <group name="Object_98" scale={0}>
            <mesh name="Cube_5_44" geometry={nodes.Cube_5_44.geometry} material={materials.Cube} />
          </group>
          <group name="Object_100" scale={0}>
            <mesh name="Cube_5_45" geometry={nodes.Cube_5_45.geometry} material={materials.Cube} />
          </group>
          <group name="Object_102" scale={0}>
            <mesh name="Cube_5_46" geometry={nodes.Cube_5_46.geometry} material={materials.Cube} />
          </group>
          <group name="Object_104" scale={0}>
            <mesh name="Cube_5_47" geometry={nodes.Cube_5_47.geometry} material={materials.Cube} />
          </group>
          <group name="Object_106" scale={0}>
            <mesh name="Cube_5_48" geometry={nodes.Cube_5_48.geometry} material={materials.Cube} />
          </group>
        </group>
        <mesh name="Circle_003_11_0" geometry={nodes.Circle_003_11_0.geometry} material={materials.Circle_003} scale={0.191} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/coffee_cup-transformed.glb')
