/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coffee_paper_bag.glb 
Author: clon6767 (https://sketchfab.com/clon6767)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-paper-bag-12e825336da1435a8decc198ea9fc06d
Title: Coffee Paper Bag
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

export function CoffeePaperBagModel(props) {
  const { nodes, materials } = useGLTF('/models/coffee_paper_bag.glb')
  return (
    <group {...props} dispose={null} scale={0.4}>
        <Center>
          <mesh geometry={nodes.Object_2.geometry} material={materials.set1} rotation={[-Math.PI / 2, 0, 0]} />
        </Center>
    </group>
  )
}

useGLTF.preload('/models/coffee_paper_bag.glb')
